services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python scraper.py
    volumes:
      - ./src:/code
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: phinvads
      POSTGRES_PASSWORD: cdc
    ports:
      - 5432:5432
    restart: on-failure